version: '3.8'

services:
  mister-controller:
    # Development overrides
    volumes:
      # Mount source code for hot reload
      - ./:/app:ro
      - mister-data:/app/data
    
    # Development command with reload
    command: ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
    # More verbose logging for development
    environment:
      - LOG_LEVEL=DEBUG
    
    # Shorter health check intervals for faster feedback
    healthcheck:
      interval: 10s
      timeout: 5s